// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAy6yHc0xK9Sd7fOHAKUr5u9pmbLIVCCCw',
//     appId: '1:613966549370:web:61f8a10bb0170a66d9c6c3',
//     messagingSenderId: '613966549370',
//     projectId: 'myocirclepatientapp',
//     authDomain: 'myocirclepatientapp.firebaseapp.com',
//     storageBucket: 'myocirclepatientapp.firebasestorage.app',
//     measurementId: 'G-5MGVJJNDML',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAKL5fKWuFDy_jgVar4zxIRfoKA1QlfSws',
//     appId: '1:613966549370:android:7be321097ec2d910d9c6c3',
//     messagingSenderId: '613966549370',
//     projectId: 'myocirclepatientapp',
//     storageBucket: 'myocirclepatientapp.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAu_OgqfSqH0l4ZiZWYhwr3UcjiTejYWNU',
//     appId: '1:613966549370:ios:ce6cf74c2f5b49aad9c6c3',
//     messagingSenderId: '613966549370',
//     projectId: 'myocirclepatientapp',
//     storageBucket: 'myocirclepatientapp.firebasestorage.app',
//     iosBundleId: 'com.myocircle.app.myocircle15screens',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAu_OgqfSqH0l4ZiZWYhwr3UcjiTejYWNU',
//     appId: '1:613966549370:ios:ce6cf74c2f5b49aad9c6c3',
//     messagingSenderId: '613966549370',
//     projectId: 'myocirclepatientapp',
//     storageBucket: 'myocirclepatientapp.firebasestorage.app',
//     iosBundleId: 'com.myocircle.app.myocircle15screens',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAy6yHc0xK9Sd7fOHAKUr5u9pmbLIVCCCw',
//     appId: '1:613966549370:web:d5d987da5527e41ed9c6c3',
//     messagingSenderId: '613966549370',
//     projectId: 'myocirclepatientapp',
//     authDomain: 'myocirclepatientapp.firebaseapp.com',
//     storageBucket: 'myocirclepatientapp.firebasestorage.app',
//     measurementId: 'G-E49H215ZHX',
//   );
// }
